### ISSUE TITLE
Allow adding of a specific array of files

### ISSUE THREAD

**Issue by madeofpeople** [aymericbeaumet/metalsmith-concat#1]
Rather than just a glob.

For js files where order might matter, it would be nice to just throw in a hard-coded array, instead of pattern. Seems when I do that, I end up with a concatenited file, that contains the entire directories content (6.4 MB!)
```
    "metalsmith-concat": {
      "files": ["jspath/a_filename.js","jspath/another_filename.js"],
      "output": "js/scripts.js"
    }
```

**Comment by aymericbeaumet** [comment]
Done: https://github.com/aymericbeaumet/metalsmith-concat/pull/2
