### ISSUE TITLE
Files deleted when paired with live reload.

### ISSUE THREAD

**Issue by JuanCaicedo** [aymericbeaumet/metalsmith-concat#18]
I'm having a problem when pairing this pluging with the livereload functionality of [metalsmith-watch](https://github.com/FWeinb/metalsmith-watch). 

I have a build which concats my styles to create `styles/app.css`. When I build, this works fine. I also have metalsmith watch enabled with livereload. When livereload triggers with a file (for example `index.html`), it pushes just that file through the build. This means that when the build reaches the concat step, there are no css files in the build, so it overrides app.css with an empty file.

I've pushed a branch where I recreated this [here](https://github.com/JuanCaicedo/juancaicedo.github.io/tree/metalsmith-concat-bug). 

Another problem I foresee is that if I have two css files being concat, and I change just one, then the build would overwrite the output file with a new file that contains only one set of styles.

Let me know if you think this is more of a bug for the metalsmith-watch team, though my guess would be here.

**Comment by aymericbeaumet** [comment]
How would you patch this plugin to solve your problem? I don't see how it can properly work if the list of files is incomplete. Wouldn't it be easier if metalsmith-watch triggers a full build?

**Comment by JuanCaicedo** [comment]
I think you're right, the fix for this is probably on that end.
