### ISSUE TITLE
Allow Concatination of files outside src

### ISSUE THREAD

**Issue by RobLoach** [aymericbeaumet/metalsmith-concat#21]
Allowing concatinating files from outside the source directory would be nice.

**Comment by aymericbeaumet** [comment]
do you have a use-case for this?

**Comment by RobLoach** [comment]
1. Install jQuery with Bower
2. In the metalsmith config....
  ``` json
  {
    "plugins": {
      "metalsmith-concat": {
        "files": [
          "bower_components/jquery/jquery.js", // Outside of src directory
          "main.js" // Makes use of jQuery
        ],
        "output": "styles/app.css"
      }
    }
  }
```

**Comment by aymericbeaumet** [comment]
hum i see, i'm willing to implement something like this

i suppose we could allow to pass absolute filepaths, that would solve the issue (but only allow to do it via the API, not the JSON config, unless you want to hardcode the path, you don't)

**Comment by RobLoach** [comment]
The logic would be something like:

1. Attempt to find the file from the Metalsmith `files` array
2. If it's not found, attempt to locate it from the file system
3. Include the found file

**Comment by aymericbeaumet** [comment]
basically you want to implement a system similar to the include directories in the compilers?

**Comment by aymericbeaumet** [comment]
the default configuration would be:

```js
{
  "plugins": {
    "metalsmith-concat": {
      "root": [ "src" ]
    }
  }
}
```

which could be customized, e.g.:

```js
{
  "plugins": {
    "metalsmith-concat": {
      "root": [ "src", "bower_components", "node_modules/angular" ]
    }
  }
}
```

**Comment by aymericbeaumet** [comment]
ps: i'm not convinced by the naming `root` is not explicit enough, ideas?

**Comment by RobLoach** [comment]
Very cool... Could searchPaths default to `[ "." ]`? Then it would fallback to cwd by default.

**Comment by aymericbeaumet** [comment]
see https://github.com/aymericbeaumet/metalsmith-concat/pull/24

**Comment by aymericbeaumet** [comment]
i didn't put `['.']` as the default search path, because i want people to explicitly provide the ones they need, and only if they need to (otherwise it's highly likely to be leading to cryptic errors)

**Comment by RobLoach** [comment]
Well done! :+1:
