### ISSUE TITLE
Add sort option

### ISSUE THREAD

**Issue by gchallen** [aymericbeaumet/metalsmith-concat#25]
I'm not sure where I got the impression that if my `css` directory contained `01_foo.css` and `02_bar.css`. then `metalsmith-concat` would reliably produce the equivalent of `cat 01_foo.css 02_bar.css`. But apparently it does not. This makes the plugin hard to use in cases where you are trying to combine things that have dependencies without having to pass an array to the plugin.

It seems like a simple lexicographic sort after locating the files and before concatenating them wouldn't break anything and would enable this use pattern.

**Comment by aymericbeaumet** [comment]
i've added a simple test to make sure it's following the metalsmith files object keys order (https://github.com/aymericbeaumet/metalsmith-concat/commit/2cf1421aedf518d240a1ee461b913fb90adcd8e0)

can you provide a failing test so that i can narrow down this issue?

**Comment by aymericbeaumet** [comment]
if you find yourself in a situation where you want to sort the results in a different order, i might add an option for that. but the default is to respect the metalsmith `files` object keys order
