### ISSUE TITLE
writing files with strings vs Buffers?

### ISSUE THREAD

**Issue by kenhoff** [aymericbeaumet/metalsmith-concat#27]
Hey @aymericbeaumet - I was passing some `metalsmith-concat`enated files to `metalsmith-layouts`, and nothing was getting generated. 

Turns out that `metalsmith-layouts` was silently failing (which is a separate issue), because it was expecting a utf-8 encoded Buffer, but the contents of the newly `metalsmith-concat`enated file was a string.

Just wanted to check here and see, is that expected? My experience with Metalsmith is that file contents are stored as Buffers, and it seems like `metalsmith-concat` is spitting out file contents as strings. 

If this is intended, no worries, and if not, happy to take a whack at it and send a PR your way, just let me know.

Thanks!

**Comment by aymericbeaumet** [comment]
Thanks for reporting 👍 Fixed since `6.0.0`
