### ISSUE TITLE
Empty dist file

### ISSUE THREAD

**Issue by Jornve** [aymericbeaumet/metalsmith-concat#29]
This plugin is not working anymore. The dist file is generated but remains empty.

**Comment by aymericbeaumet** [comment]
Can you share a code snippet?

**Comment by Jornve** [comment]
Sure, this is my build file: 

`'use strict';

let
    consoleLog = true, // set true for metalsmith file and meta content logging
    devBuild = ((process.env.NODE_ENV || '').trim().toLowerCase() !== 'production'),
    pkg = require('./package.json'),

    dir = {
        base: __dirname + '/',
        source: './src/',
        dest: './build/'
    },


    metalsmith = require('metalsmith'),
    markdown = require('metalsmith-markdown'),
    layouts = require('metalsmith-layouts'),
    handlebars = require('handlebars'),
    collections = require('metalsmith-collections'),
    permalinks = require('metalsmith-permalinks'),
    assets = require('metalsmith-assets'),
    browserSync = require('metalsmith-browser-sync'),
    browserify = require('metalsmith-browserify'),
    fingerprint = require('metalsmith-fingerprint'),
    concat = require('metalsmith-concat'),

    siteMeta = {
        devBuild: devBuild,
        version: pkg.version,
        domain: devBuild ? 'http://127.0.0.1' : 'https://www.example.com', // set domain
        rootpath: devBuild ? null : 'path to rootpath', // set absolute path (null for relative)
        site: {
            name: 'Electroniq',
            description: "Electroniq is astrophysicist (and retro music enthusiast) Tara Himmels' blog."
        }
    },

    templateConfig = {
        engine: 'handlebars',
        directory: dir.source + 'template/',
        partials: dir.source + 'partials/',
        default: 'index.html'
    };

console.log((devBuild ? 'Development' : 'Production'), 'build, version', pkg.version);

let ms = metalsmith(dir.base)

    .clean(!devBuild) // clean folder before a production build
    .source(dir.source + 'data/') // source folder (src/html/)
    .destination(dir.dest) // build folder (build/)
    .metadata(siteMeta) // add meta data to every page
    .use(markdown())
    .use(layouts(templateConfig)) // layout templating
    .use(permalinks({ // generate permalinks
        pattern: ':mainCollection/:title'
    }))

    .use(browserSync({
        server: "./build",
        files: ["./src/**/*", "layouts/**/*"]
    }))

.use(concat({
        files: [
            'bootstrap.css', // will be resolved from the node_modules
            'main.css' // will be resolved from the directory given to Metalsmith
        ],
        searchPaths: [ 'src/assets/css' ],
        output: "assets/css/bundle.css"
    }))
.build(function (err) {
        if (err) {
            console.log(err);
        }
        else {
            console.log('AS static site built!');
        }
    });`

**Comment by aymericbeaumet** [comment]
1) metalsmith-concat will only concatenate what it matches the [minimatch](https://github.com/isaacs/minimatch) patterns you give him, if you end up having html in your `styles/app.css`, something is generating html in files matching the pattern `styles/**/*.css` early on.

2) searchPaths [ignores the `src` directory](https://github.com/aymericbeaumet/metalsmith-concat/blob/01d75f079cb111fd4486429bc205c8d1366ad5e8/lib/index.js#L135), so this is the expected behaviour, I've added [a note in the readme](https://github.com/aymericbeaumet/metalsmith-concat/blob/1626cf36942bb08dc0fb4497675de88e643d268b/readme.md#searchpaths) about this. You can do something along the lines of:

```js
const cssAsset = file => `src/assets/css/${file}`;

// ...

.use(concat({
  files: ['bootstrap.css', 'main.css'].map(cssAsset),
  output: 'assets/css/bundle.css',
 }))
```
