### ISSUE TITLE
Lumens

### ISSUE THREAD

**Issue by sivadi** [aymericbeaumet/metalsmith-concat#32]
Vadim February 21, 2018 19:06
Hello! Faced such a problem. I can not send coins from my wallet writes such a mistake .. 
{ 
"type": "https://stellar.org/horizon-errors/transaction_failed", 
"title": "Transaction Failed", 
"status": 400, 
"detail": "The transaction failed when submitted to the stellar network. The extras.result_codes field on this response contains further details. Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html", 
"instance": "horizon-001a/71LV2KXh2A-72849508", 
"extras": { 
"envelope_xdr": "AAAAAOt0auvBKc3j0AP633hqvJktLnqNtmmXgn10O/KJPFLEAAAAZADzw0MAAAABAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAq2OR6BMg2SaeqkLqwpebz+1JZnhKV4eqluP9fJOubPMAAAAAAAAAAA7msoAAAAAAAAAAAYk8UsQAAABA56SIUdNMxvVJoLVt3orBQxa8upgS3y+x2ak+ve3s/2rNQOfn4rXDijW2VkXStnouk7vG1878P50GzieSMLjXDA==",
"result_codes": { 
"transaction": "tx_failed", 
"operations": [ 
"op_bad_auth" 
] 
}, 
"result_xdr": "AAAAAAAAAGT/////AAAAAf////8AAAAA" 
} 
}. 
the purse 788 lumens How do I get my money back?

**Comment by aymericbeaumet** [comment]
Please be more explicit regarding how this error is caused by metalsmith-concat.

**Comment by sivadi** [comment]
I don't know..
