### ISSUE TITLE
file paths should be normalized

### ISSUE THREAD

**Issue by oupala** [aymericbeaumet/metalsmith-concat#8]
When using the array syntax for metalsmith-concat (#2), it appears that file paths should be normalized otherwise, I get an error that tells that the file does not exist :

`Error: js/jquery-2.1.1.min.js does not exist`

And it's right, on windows the file is at `js\\jquery-2.1.1.min.js`.

File path should be normalized to be OS agnostic.

You can find more information in an article that helps [Writing cross-platform Node.js](http://shapeshed.com/writing-cross-platform-node/).

**Comment by aymericbeaumet** [comment]
Hey @oupala,

thanks for reporting the issue, didn't test it on Windows to be honest. I pushed a new version [here](https://github.com/aymericbeaumet/metalsmith-concat/tree/refactoring), could you give it a try?

**Comment by oupala** [comment]
As far as I tested the *refactoring* branch, it works perfectly.

Thanks for fixing the bug !

I let you close the issue once the new version is released.

**Comment by aymericbeaumet** [comment]
Landed on npm
